### PR TITLE
Fix unicode path on windows

### LINKED ISSUE #152: Unable to open image with Chinese path using TIFF.open
Is there any way to solve this problem

### PR DESCRIPTION
**Pull request by One-sixth**
Fix #152

### CODE REVIEW

**Comment by pearu** [comment]
See https://github.com/pearu/pylibtiff/issues/152#issuecomment-1693096484, this is to make sure that the issue is not about the user environment.

**Comment by One-sixth** [comment]
@pearu I just saw it. The comment has been updated.

**Review by pearu — APPROVED** [review]
LGTM! Thanks, @One-sixth!

**Review by djhoese — COMMENTED** [review]
I'm not sure I agree or disagree with this fix. From what I remember of the discussion in the related issue this seems like a bug in the python standard library or a misconfiguration of the user's system. It is hard to test for anyone without a Windows system with problematic encodings configured. @pearu feel free to merge.

...I do think this duplicate logic could be put into a helper function (ex. `_fsencode`) to avoid later fixes to one of these blocks but not the other.

**Pull request merged**
