### PR TITLE
Fix libtiff.info CLI on MacOS/Linux

### PR DESCRIPTION
**Pull request by Dennis-Johnson**
Hi, 

This fixes this issue #163 encountered with the libtiff.info CLI. Verified on MacOS & Linux.

### CODE REVIEW

**Comment by djhoese** [comment]
Thanks for the PR! Just curious, I'm not a user of this script, but is this matplotlib try/except block even needed? Maybe in old matplotlib it was nice to force it to a particular backend, but since I removed the GUI functionality, I don't see any use of matplotlib in these scripts. Right?

Additionally, the `parser.run_methods = ["subcommand"]` thing...I don't think that does anything does it?

@pearu any memory of what this stuff was used for?

**Comment by djhoese** [comment]
Yeah I can't find anything else in pylibtiff (even in the old GUI interface) that used matplotlib. I'm not sure it was used in any modern version of the code (last 10 years?) unless I'm missing something. Maybe it was just there for debugging in the past?

**Comment by pearu** [comment]
> parser.run_methods = ["subcommand"]

I don't recall anymore why it is there. Looks safe to remove it.

**Comment by djhoese** [comment]
@Dennis-Johnson Would you mind updating this PR and just completely removing that try/except?

**Comment by djhoese** [comment]
Note: The setuptools_scm failure is a known issue. I'll work on fixing that in a separate PR.

**Comment by djhoese** [comment]
Or... @Dennis-Johnson I need to make a release to fix this setuptools scm error in the CI. Do you mind if I just fix this myself?

Side note: For future reference, I'd recommend always creating a new branch for any changes you make. Otherwise it makes it hard to pull in upstream changes into your pull requests.

**Comment by djhoese** [comment]
Replaced by #166. Let me know if you have a problem with this @Dennis-Johnson

**Comment by Dennis-Johnson** [comment]
Thanks.

**Pull request closed without merging**
