### PR TITLE
Add header files for tiff 4.0.7 and 4.0.8.

### PR DESCRIPTION
**Pull request by manthey**
These are identical to the 4.0.6 header files.

### CODE REVIEW

**Comment by brianhelba** [comment]
@pearu This would greatly help in my usage of PyLibTiff in a Python virtualenv. Can it be merged?

**Comment by brianhelba** [comment]
Thanks @pearu . Are you able to make a release? It would greatly help our downstream usage.

**Comment by pearu** [comment]
Done: libtiff 0.4.1 has been released. See https://pypi.python.org/pypi/libtiff. Please try to use it via pip (or equivalent tool).

**Comment by brianhelba** [comment]
Great, thanks!

**Pull request merged**
