### PR TITLE
Add libtiff 4.6.0

### PR DESCRIPTION
**Pull request by djhoese**

### CODE REVIEW

**Comment by djhoese** [comment]
Lots of these warnings:

```

libtiff/tests/test_lzw.py::test_encode
  /home/runner/work/pylibtiff/pylibtiff/libtiff/tests/test_lzw.py:29: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 732 to uint8 will fail in the future.
  For the old behavior, usually:
      np.array(value).astype(dtype)
  will give the desired result (the cast overflows).
    numpy.array(list(range(400000)), numpy.uint8),
```

I'll implement the suggested change to preserve old behavior because I'm guessing this was just a lazy way to request repeated indices that wrapped around (ex. 254, 255, 0, 1, 2, ...).

**Comment by djhoese** [comment]
Now I'm getting lots of:

```
libtiff/tests/test_tiff_image.py 277:292,.........................TIFFFetchNormalTag: Warning, ASCII value for tag "ImageDescription" does not end in null byte.
.TIFFFetchNormalTag: Warning, ASCII value for tag "ImageDescription" does not end in null byte.
.TIFFFetchNormalTag: Warning, ASCII value for tag "ImageDescription" does not end in null byte.
.TIFFFetchNormalTag: Warning, ASCII value for tag "ImageDescription" does not end in null byte.
.TIFFFetchNormalTag: Warning, ASCII value for tag "ImageDescription" does not end in null byte.
.TIFFFetchNormalTag: Warning, ASCII value for tag "ImageDescription" does not end in null byte.
.TIFFFetchNormalTag: Warning, ASCII value for tag "ImageDescription" does not end in null byte.
.TIFFFetchNormalTag: Warning, ASCII value for tag "ImageDescription" does not end in null byte.
.TIFFFetchNormalTag: Warning, ASCII value for tag "ImageDescription" does not end in null byte.
.TIFFFetchNormalTag: Warning, ASCII value for tag "ImageDescription" does not end in null byte.
.TIFFFetchNormalTag: Warning, ASCII value for tag "ImageDescription" does not end in null byte.
.TIFFFetchNormalTag: Warning, ASCII value for tag "ImageDescription" does not end in null byte.
```

Do these concern you @pearu or should they be expected in some of these tests?

**Comment by djhoese** [comment]
@pearu Let me know soon if you have any issues with the changes in this PR and my comment above about the warnings. Otherwise I'm going to approve my pull request, merge it, and release it so I can update the conda-forge package.

**Review by pearu — APPROVED** [review]
The tiff_h_4_6_0.py file looks good.

Resolving numpy deprecation warnings makes sense.

Disabling print function calls is a halfway solution but I don't have better suggestions right now.

Thanks, @djhoese!

**Pull request merged**
