### PR TITLE
Change matplotlib backend to GTk3Agg for POSIX

### PR DESCRIPTION
**Pull request by djhoese**
Replaces #164. This also drops a `wx` import in addition to dropping the `matplotlib` import we talked about in #164. @pearu thoughts?

CC @dennis-johnson

### CODE REVIEW

**Comment by djhoese** [comment]
And @pearu I'm not sure if you did this on purpose or if it is an update from github, but I can no longer merge my PRs unless you approve them. If you didn't like me merging my own PRs then OK, but if you are OK with it then I'll have to move a little slower on some of these things.

**Review by pearu — APPROVED** [review]
LGTM! Thanks, @djhoese!

**Comment by pearu** [comment]
> And @pearu I'm not sure if you did this on purpose or if it is an update from github, but I can no longer merge my PRs unless you approve them.

@djhoese Ideally, each PR should be reviewed but since the list of reviewers in pylibtiff repo is very short, I'll see if I can relax the procedure for merging PRs.

**Comment by djhoese** [comment]
Exactly. It isn't great, but too few maintainers. Otherwise, we get to a point like yesterday where no one could install anything that depended on pylibtiff for a while and one of us if just waiting on the other to wake up or get back from vacation.

**Comment by djhoese** [comment]
I'll make a release with this today.

**Pull request merged**
